# Generated by Django 3.2.5 on 2021-09-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Midstream_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_representative', models.CharField(max_length=100, verbose_name='公司負責人')),
                ('person_ID', models.CharField(help_text='格式為身分證字號（1 碼，限大寫英文字）+ 身分字號（最長 9 碼，限數字)', max_length=10, verbose_name='負責人證號')),
                ('local_phone', models.CharField(help_text='市話，ex：02-1234-5678，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='負責人市內電話')),
                ('cell_phone', models.CharField(help_text='手機，ex: 0912-123-456，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='負責人手機')),
                ('person_email', models.EmailField(blank=True, default='', help_text='★★★必需的。 添加有效的電子郵件地址', max_length=255, verbose_name='負責人信箱')),
                ('create_date_p', models.DateTimeField(auto_now_add=True, verbose_name='儲存日期')),
                ('last_modified_p', models.DateTimeField(auto_now=True, verbose_name='最後修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Midstream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_Name', models.CharField(max_length=255, verbose_name='公司名稱')),
                ('uniform_numbers', models.CharField(blank=True, help_text='企業請提供統一編號 (8碼，ex: 12345678)；個人請提供身分證字號', max_length=8, verbose_name='統一編號')),
                ('registration_status', models.CharField(blank=True, help_text='自行填寫格式為 :  "停業"&nbsp;&nbsp;&nbsp;"未申請"&nbsp;&nbsp;&nbsp;"核准設立 - 合夥/各人 (核准文號: 1090821289)"&nbsp;&nbsp;&nbsp;"其他原因"。 ', max_length=100, null=True, verbose_name='註冊狀態')),
                ('register_phone', models.CharField(blank=True, help_text='手機，ex：0912-345-678，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='登記電話')),
                ('registered_address', models.CharField(max_length=255, verbose_name='登記地址')),
                ('company_email', models.EmailField(blank=True, default='', help_text='★★★必需的。 添加有效的電子郵件地址', max_length=255, verbose_name='郵件信箱')),
                ('company_website', models.URLField(max_length=255, verbose_name='公司網站')),
                ('company_photos', models.ImageField(blank=True, upload_to='companies', verbose_name='公司照片')),
                ('registration_type', models.CharField(help_text='ex: 商業登記', max_length=255, verbose_name='登記種類')),
                ('registration_authority', models.CharField(help_text='ex: XX(縣市)政府', max_length=255, verbose_name='登記機關')),
                ('company_notes', models.TextField(blank=True, verbose_name='公司筆記')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='儲存日期')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最後修改日期')),
                ('company_principal', models.ForeignKey(blank=True, default='', help_text='公司負責人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midstream', to='midstream.midstream_person')),
            ],
        ),
    ]
