# Generated by Django 2.0.1 on 2021-11-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midstream', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midstream',
            options={'get_latest_by': ['-priority', 'order_date'], 'ordering': ['-create_date', '-last_modified']},
        ),
        migrations.AlterField(
            model_name='midstream',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='midstream_person',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
