# Generated by Django 3.2.5 on 2021-09-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midstream', '0002_alter_midstream_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midstream',
            name='company_email',
            field=models.EmailField(blank=True, default='', help_text='★★★必需的。 添加有效的電子郵件地址', max_length=255, unique=True, verbose_name='郵件信箱'),
        ),
        migrations.AlterField(
            model_name='midstream_person',
            name='person_email',
            field=models.EmailField(blank=True, default='', max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
