# Generated by Django 3.2.5 on 2021-10-04 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Vendor_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendors_stand_principal', models.CharField(blank=True, help_text='', max_length=255, verbose_name='攤位負責人')),
                ('vendors_stand_certificate_num', models.CharField(blank=True, help_text='格式為身分證字號（1 碼，限大寫英文字）+ 身分字號（最長 9 碼，限數字', max_length=10, verbose_name='負責人證號')),
                ('telephone', models.CharField(blank=True, help_text='手機，ex：0912345678，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='電話')),
                ('address', models.CharField(blank=True, help_text='', max_length=255, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Mass_Mer_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_mer_principal', models.CharField(blank=True, help_text='', max_length=255, verbose_name='量販店負責人')),
                ('certificate_num_principal', models.CharField(blank=True, help_text='格式為身分證字號（1 碼，限大寫英文字）+ 身分字號（最長 9 碼，限數字', max_length=10, verbose_name='負責人證號')),
                ('telephone', models.CharField(blank=True, help_text='手機，ex：0912345678，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='手機電話')),
                ('address', models.CharField(blank=True, help_text='', max_length=255, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Other_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_principal', models.CharField(blank=True, help_text='', max_length=255, verbose_name='其他負責人')),
                ('other_certificate_num', models.CharField(blank=True, help_text='格式為身分證字號（1 碼，限大寫英文字）+ 身分字號（最長 9 碼，限數字', max_length=10, verbose_name='負責人證號')),
                ('telephone', models.CharField(blank=True, help_text='手機，ex：0912345678，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='電話')),
                ('address', models.CharField(blank=True, help_text='', max_length=255, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Retail_Factory_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_factory_principal', models.CharField(blank=True, help_text='', max_length=255, verbose_name='工廠負責人')),
                ('retail_factory_certificate_num', models.CharField(blank=True, help_text='格式為身分證字號（1 碼，限大寫英文字）+ 身分字號（最長 9 碼，限數字', max_length=10, verbose_name='負責人證號')),
                ('telephone', models.CharField(blank=True, help_text='手機，ex：0912345678，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='手機號碼')),
                ('address', models.CharField(blank=True, help_text='', max_length=255, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Storefront_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storefront_principal', models.CharField(blank=True, help_text='', max_length=255, verbose_name='店面負責人')),
                ('storefront_certificate_num', models.CharField(blank=True, help_text='格式為身分證字號（1 碼，限大寫英文字）+ 身分字號（最長 9 碼，限數字', max_length=10, verbose_name='負責人證號')),
                ('telephone', models.CharField(blank=True, help_text='手機，ex：0912345678，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='電話')),
                ('address', models.CharField(blank=True, help_text='', max_length=255, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Storefront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司(攤位)名稱')),
                ('company_phone', models.CharField(blank=True, help_text='手機，ex：0225445666，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='公司電話')),
                ('cell_phone', models.CharField(blank=True, help_text='手機，ex：0912345678，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='手機電話')),
                ('address', models.CharField(max_length=255, verbose_name='登記地址')),
                ('uniform_numbers', models.CharField(blank=True, help_text='企業請提供統一編號 (8碼，ex: 12345678)；個人請提供身分證字號', max_length=8, verbose_name='統一編號')),
                ('area', models.CharField(blank=True, help_text='ex: 文山區', max_length=5, verbose_name='區域')),
                ('regional_app_num', models.CharField(blank=True, help_text='ex: 1234567890', max_length=10, verbose_name='地區申請編號')),
                ('cooperate_businmen', models.CharField(blank=True, help_text='', max_length=255, verbose_name='合作的中游商')),
                ('mailbox', models.CharField(blank=True, help_text='企業請提供統一編號 (8碼，ex: 12345678)；個人請提供身分證字號', max_length=8, verbose_name='信箱')),
                ('capital', models.CharField(blank=True, help_text='ex: 200,000,000', max_length=255, verbose_name='資本額')),
                ('approved_date', models.DateTimeField(auto_now_add=True, help_text='', verbose_name='核准設立日期')),
                ('company_principal', models.ForeignKey(blank=True, default='', help_text='公司負責人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midstream', to='mass_mer.storefront_person')),
            ],
        ),
        migrations.CreateModel(
            name='Retail_Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名稱')),
                ('company_phone', models.CharField(blank=True, help_text='手機，ex：0225445666，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='公司電話')),
                ('cell_phone', models.CharField(blank=True, help_text='手機，ex：0912345678，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='手機電話')),
                ('address', models.CharField(max_length=255, verbose_name='登記地址')),
                ('uniform_numbers', models.CharField(blank=True, help_text='企業請提供統一編號 (8碼，ex: 12345678)；個人請提供身分證字號', max_length=8, verbose_name='統一編號')),
                ('area', models.CharField(blank=True, help_text='ex: 文山區', max_length=5, verbose_name='區域')),
                ('regional_app_num', models.CharField(blank=True, help_text='ex: 1234567890', max_length=10, verbose_name='地區申請編號')),
                ('cooperate_businmen', models.CharField(blank=True, help_text='', max_length=255, verbose_name='合作的中游商')),
                ('mailbox', models.CharField(blank=True, help_text='企業請提供統一編號 (8碼，ex: 12345678)；個人請提供身分證字號', max_length=8, verbose_name='信箱')),
                ('capital', models.CharField(blank=True, help_text='ex: 200,000,000', max_length=255, verbose_name='資本額')),
                ('approved_date', models.DateTimeField(auto_now_add=True, help_text='', verbose_name='核准設立日期')),
                ('company_principal', models.ForeignKey(blank=True, default='', help_text='公司負責人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midstream', to='mass_mer.retail_factory_person')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名稱')),
                ('company_phone', models.CharField(blank=True, help_text='手機，ex：0225445666，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='公司電話')),
                ('cell_phone', models.CharField(blank=True, help_text='手機，ex：0912345678，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='手機電話')),
                ('address', models.CharField(max_length=255, verbose_name='登記地址')),
                ('uniform_numbers', models.CharField(blank=True, help_text='企業請提供統一編號 (8碼，ex: 12345678)；個人請提供身分證字號', max_length=8, verbose_name='統一編號')),
                ('area', models.CharField(blank=True, help_text='ex: 文山區', max_length=5, verbose_name='區域')),
                ('regional_app_num', models.CharField(blank=True, help_text='ex: 1234567890', max_length=10, verbose_name='地區申請編號')),
                ('cooperate_businmen', models.CharField(blank=True, help_text='', max_length=255, verbose_name='合作的中游商')),
                ('mailbox', models.CharField(blank=True, help_text='企業請提供統一編號 (8碼，ex: 12345678)；個人請提供身分證字號', max_length=8, verbose_name='信箱')),
                ('capital', models.CharField(blank=True, help_text='ex: 200,000,000', max_length=255, verbose_name='資本額')),
                ('approved_date', models.DateTimeField(auto_now_add=True, help_text='', verbose_name='核准設立日期')),
                ('company_principal', models.ForeignKey(blank=True, default='', help_text='公司負責人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midstream', to='mass_mer.other_person')),
            ],
        ),
        migrations.CreateModel(
            name='Mass_Mer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名稱')),
                ('company_phone', models.CharField(blank=True, help_text='手機，ex：0225445666，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='公司電話')),
                ('cell_phone', models.CharField(blank=True, help_text='手機，ex：0912345678，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='手機電話')),
                ('address', models.CharField(max_length=255, verbose_name='登記地址')),
                ('uniform_numbers', models.CharField(blank=True, help_text='企業請提供統一編號 (8碼，ex: 12345678)；個人請提供身分證字號', max_length=8, verbose_name='統一編號')),
                ('area', models.CharField(blank=True, help_text='ex: 文山區', max_length=5, verbose_name='區域')),
                ('regional_app_num', models.CharField(blank=True, help_text='ex: 1234567890', max_length=10, verbose_name='地區申請編號')),
                ('cooperate_businmen', models.CharField(blank=True, help_text='', max_length=255, verbose_name='合作的中游商')),
                ('mailbox', models.CharField(blank=True, help_text='企業請提供統一編號 (8碼，ex: 12345678)；個人請提供身分證字號', max_length=8, verbose_name='信箱')),
                ('capital', models.CharField(blank=True, help_text='ex: 200,000,000', max_length=255, verbose_name='資本額')),
                ('approved_date', models.DateTimeField(auto_now_add=True, help_text='', verbose_name='核准設立日期')),
                ('company_principal', models.ForeignKey(blank=True, default='', help_text='公司負責人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midstream', to='mass_mer.mass_mer_person')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='攤位名稱')),
                ('company_phone', models.CharField(blank=True, help_text='手機，ex：0225445666，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='公司電話')),
                ('cell_phone', models.CharField(blank=True, help_text='手機，ex：0912345678，***直接輸入數字，不用此符號「-」', max_length=10, verbose_name='手機電話')),
                ('address', models.CharField(max_length=255, verbose_name='登記地址')),
                ('uniform_numbers', models.CharField(blank=True, help_text='企業請提供統一編號 (8碼，ex: 12345678)；個人請提供身分證字號', max_length=8, verbose_name='統一編號')),
                ('area', models.CharField(blank=True, help_text='ex: 台北市', max_length=5, verbose_name='區域')),
                ('vendors_stand_num', models.CharField(blank=True, help_text='需10碼，ex: 1234567890', max_length=5, verbose_name='攤位編號')),
                ('regional_app_num', models.CharField(blank=True, help_text='ex: 1234567890', max_length=10, verbose_name='地區申請編號')),
                ('cooperate_businmen', models.CharField(blank=True, help_text='', max_length=255, verbose_name='合作的中游商')),
                ('mailbox', models.CharField(blank=True, help_text='企業請提供統一編號 (8碼，ex: 12345678)；個人請提供身分證字號', max_length=8, verbose_name='信箱')),
                ('capital', models.CharField(blank=True, help_text='ex: 200,000,000', max_length=255, verbose_name='資本額')),
                ('approved_date', models.DateTimeField(auto_now_add=True, help_text='', verbose_name='核准設立日期')),
                ('company_principal', models.ForeignKey(blank=True, default='', help_text='公司負責人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midstream', to='mass_mer.food_vendor_person')),
            ],
        ),
    ]
