# Generated by Django 3.2.5 on 2021-09-16 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('description', models.TextField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254, verbose_name='email')),
                ('website', models.URLField(default='')),
                ('phone', models.CharField(default=0, max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
    ]
